import React from "react";
import { StytchProvider } from "@/providers/StytchProvider";

import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./globals.css";

const inter = Montserrat({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "InFuse Wallet Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <StytchProvider>{children}</StytchProvider>
      </body>
    </html>
  );
}
